### ISSUE TITLE
Fix restaurant card mobile view

### ISSUE THREAD

**Issue by ExpressHermes** [ExpressHermes/Hunger-Book#1]
In mobile view, the text inside the restaurant card overlaps.

**Comment by outofgamut** [comment]
I can take this.

**Comment by ExpressHermes** [comment]
Sure.

**Comment by sagarparmar881** [comment]
I can handle this.

**Comment by ExpressHermes** [comment]
Hey @sagarparmar88, I think @outofgamut is already working on it.

**Comment by ExpressHermes** [comment]
@outofgamut are you working on it?

**Comment by hambali999** [comment]
Hi! can i take over this issue? this is my first time.
I was looking into the herokuapp for this and it seems that the text didnt overlap

**Comment by ExpressHermes** [comment]
Fixed in #6
