### ISSUE TITLE
Remove repeated code in templates

### ISSUE THREAD

**Issue by ExpressHermes** [ExpressHermes/Hunger-Book#2]
The templates currently have lot of repeated code. Use template inheritance to remove repeated code.

**Comment by Tawishi** [comment]
I would like to work on this issue.

**Comment by ExpressHermes** [comment]
@Tawishi Sure. Go ahead.

**Comment by Tawishi** [comment]
How do I proceed?

**Comment by ExpressHermes** [comment]
Have you worked with Django or Flask?

**Comment by Tawishi** [comment]
I have worked with Django in Python.

**Comment by ExpressHermes** [comment]
Check out [this link](https://flask.palletsprojects.com/en/1.1.x/patterns/templateinheritance/).

**Comment by ExpressHermes** [comment]
@Tawishi are you working on this?

**Comment by Tawishi** [comment]
Yes @ExpressHermes. I am trying. Will contact you in case I need help.

**Comment by ExpressHermes** [comment]
Fixed in #5.

**Comment by ExpressHermes** [comment]
@Tawishi you can work on any other issue or create a new one if you have any suggestions. This issue has been resolved. Thank you for your contribution.
